### PR TITLE
Fix disconnect issue (MAX_CLIENTS=6)

### PR DESCRIPTION
**Pull request by patters**
- Add error handler to the XMPP 'login' client
- Reject promises in both error handlers
- Enable auto-reconnection

### CODE REVIEW

**Comment by patters** [comment]
This fixes #34. I've been running it for a few weeks and haven't had any problems; previously, Homebridge would crash daily because of this issue.

**Comment by kobim** [comment]
Hi @patters,
I've been trying to resolve this on [my own too](https://github.com/swissmanu/harmonyhubjs-client/compare/develop...kobim:fix/connection_errors) and I have some questions regarding your implementation:

1. Why do you use `reconnect: true`? isn't that the user's responsibility to implement his own reconnection policy upon error (e.g throttling)
1.1. If already using `reconnect`, why is it omitted from `loginWithIdentity`?
2. Any reason not to filter the error reason before trying to reconnect? Especially in `loginWithIdentity`, where the client might receive errors not related to function but to the consumer (remember the `xmppClient` is being passed to the consumer for the session.)

Other than that, this one also fixes #33 (and around 9 issues from homebridge-harmonyhub as well.)

**Comment by AirBorne04** [comment]
since this repo seems to be abandoned i created an updated package which includes some of the here available pull requests, hop over to [@harmonyhub](https://github.com/AirBorne04/harmonyhub) and give it a try.

**Comment by nicoduj** [comment]
Hi all, I tried to put the fix manually, will keep this thread update dif it is good for me . By the way, any possibility to update the package and homebridge-harmonyhub on npm also in order to have this directly through homebridge ?

**Comment by nicoduj** [comment]
Hi, 

So @patters  fix didn't worked for me : homebridge was not crashed, but harmony plugin was not responding until I restarted homebridge server. I put @kobin fix in place, let's see tomorrow :)

**Comment by swissmanu** [comment]
thank you for your change. it will be part of the next released version.

**Pull request merged**
